### ISSUE TITLE
[Question] Get callback is not called

### ISSUE THREAD

**Issue by imadari** [savoirfairelinux/opendht#163]
I have the following use case:

- Node 1 starts and put() one key and few values.
- Node 1 periodically (every 5 seconds) calls get() and writes the values to the standard output.
- Node 2 joins to node 1, calls get() periodically and writes the values to the std out.
- Node 2 disconnects.
- Node 1 get() callback never called after node 2 disconnected.
- If node 2 reconnects, all the get() returns with bunch of values at the same time.

Are there any way to retrieve the values if the node become "isolated"? (after node2 disconnects).

**Comment by sim590** [comment]
> Node 1 get() callback never called after node 2 disconnected.

Do you mean the `DoneCallback` or the `GetCallback`? When the second node disconnects, the other node entered a disconnected state. Therefor, it should fail on all subsequent calls and return immediately. Recent changes in OpenDHT were somewhat drastic and may have altered some use cases around the behavior of callbacks being called.

Actually, could you provide us with relevant snippets of code so that we can clearly understand your use case? If you can be more clear about your test, we could may be trace a bug.

> Are there any way to retrieve the values if the node become "isolated"? (after node2 disconnects).

Values are stored on the 8 closest nodes around the hash value you use. So, if your total network only counts 2<8 nodes, then all nodes should store the values. When you call the `get` method, your local node should return values stored locally in the present case. Otherwise, it depends if your local nodes is close enough.

**Comment by sim590** [comment]
@imadari: We have been working on enhancing OpenDHT connectivity changes handling, see 620868b. In fact, we have found 2 bugs which seems to explain the situation you were experiencing.

> When the second node disconnects, the other node entered a disconnected state. Therefor, it should fail on all subsequent calls and return immediately.

As I have said above, when entering the "disconnected" state, callbacks should fail. However, before 620868b, there was a bug where "disconnected state" could not be reached in a reasonable amount of time. This is now in master branch.

I'm closing this issue. Feel free to reopen if you feel your question has not been answered appropriately.

**Comment by imadari** [comment]
Okay, got it! thanks!

Few details about our use case: we are trying to use OpenDHT for service discovery. However some of the services may run locally (on the local node). So if the node disconnected and there is no active connection, some of the services can be found locally.

I used the same test code what I mentioned in #162, but I just the `odhtget` or `odhtput` randomly.

**Comment by sim590** [comment]
@imadari. My last response was correct, but doesn't consist in the only explanation for the experience you're having. Fondamental design choices were made previously so that a node can only work when conected to the network, and can't operate standalone, in which case all operations would fail.
That being said, your use case highlights that those choices may need to change. We are presently discussing how to appropriately cover local operations. In the mean time, to achieve your goal, you'd have to use two nodes connected locally.
