### ISSUE TITLE
cannot bootstrap from local test network

### ISSUE THREAD

**Issue by Silur** [savoirfairelinux/opendht#172]
Runing `dhnode -p 4422` creates the local dht node, however the example python code provided in the readme does not work with `'127.0.0.1'`. Writing takes forever and freeze the script.
 
Arch linux 4.9.6-1
openDHT freshly installed from git

**Comment by aberaud** [comment]
Hello,
To avoid accidental transmission of unroutable loopback addresses to remote nodes, loopback IPs can't currently be used, you can use any other IP address configured on your interface, for instance your local network address.
Since there seems to be a need to use loopback addresses (for testing purposes etc.), I will add a configuration option to allow them.

**Comment by sim590** [comment]
@Silur By the way, if you want to get answers on IRC, you'd have to stick around a bit longer. We always answer, in time. Thirty minutes in the morning is not enough though :wink:

**Comment by Silur** [comment]
yes thanks
