### ISSUE TITLE
put which overwrites value, not appends to the list

### ISSUE THREAD

**Issue by microo8** [savoirfairelinux/opendht#18]
I would be great to have a put action, that does not append a value to the value list but overwrites the value. Would it be posible?

Now it is like: `dht[key].append(value)`
and the new put action would be: `dht[key] = value`

**Comment by aberaud** [comment]
Hello,
It's supported by OpenDHT, however for security reasons, it's currently only possible for signed values, so that you can only modify your own values.

It's unavailable for plain (unsigned) values and for encrypted values because encrypted values signature is hidden inside the encryption, so the signature can't be verified except by the recipient.

Every value has an 64 bits ID (different from the key). If not set, this ID is randomly assigned (when performing put).
To update an existing signed value, you should perform a put with the same value ID.
You should be able to do something like:

```c++
// put initial value
auto value = std::make_shared<dht::Value>(your_data);
node.put_signed(key, value);

// ...

// update the value
value->data = {your_new_data};
node.put_signed(key, value);

// update the value (2nd option)
dht::Value new_value {your_new_data};
new_value.id = value->id;
node.put_signed(key, std::move(new_value));
```

**Comment by microo8** [comment]
Thank you, I didn't know that the value id can be set.

**Comment by bkggkt3d** [comment]
Sorry for continuing this closed topic:
Reusing the Value-ID makes it difficult for stopped/restarted application-processes to update a key. The application needs to persist all Value-IDs of all keys somewhere to disk to reuse them later for updates...

One more question in this direction:
Lets assume I don't overwrite the same key Value-ID, simply using .put() and randomly create a new Value-ID with each key update: How does the .get() knows which of the found key-values is the actual / latest one?

**Comment by aberaud** [comment]
Thanks for your comment,
At some point you would need a way to retrieve the value, the same way that you would need to remember a path and filename to access a file.

Get() will give you a list of values for a key, like when browsing a directory. Put() will add a entry in that "directory".

There are a few ways for an application to reuse the same values without locally storing value IDs :
* Put a single signed value at a given key. When connecting again, perform a get() and check if a value signed by you is there. If so, update it, otherwise put a new value. The same technique can be used with multiple values under a same key if your app has a way to distinguish them (using the data itself). Otherwise just use different keys for different values.
* Add a timestamp or version number inside your value data, use it to identify the latest version (can also be used with encrypted data).
* Deterministically compute a value ID (and key?) from data. However this is discouraged because some other users could then attack your app by putting other values at the same IDs, preventing you to use those IDs.

If you think about a better way, suggestions are welcome :-) What kind of use-case are you thinking about ?

**Comment by aberaud** [comment]
Reclosing the issue,
However don't hesitate to make comments or suggestions regarding this topic here.
