### ISSUE TITLE
No release for ring

### ISSUE THREAD

**Issue by stefan-langenmaier** [savoirfairelinux/opendht#190]
I try to package ring, but it no longer builds with the latest release of opendht (1.3.0). With master it works fine.

Could you please create a new release as I would like to avoid to depend directly on the master branch.

**Comment by sim590** [comment]
@stefan-langenmaier: Indeed, Ring doesn't have a strict policy for exclusively using releases (see the [contrib source for opendht](https://gitlab.savoirfairelinux.com/ring/ring-daemon/blob/master/contrib/src/opendht/rules.mak). It uses straight commit hashes). This is arguably bad. For instance, your intuition shows that. I share the concern. May be all of this is due to the fact that OpenDHT releases are not published fast enough or the fact that Ring doesn't have the same "release" model. Therefore, it is not straightforward for packagers what reference to use for Ring in order to sync with all other dependencies. However, all of this is depends on the point of view.

**Comment by sim590** [comment]
We have just published  a new [release](https://github.com/savoirfairelinux/opendht/releases/tag/1.3.1).

**Comment by stefan-langenmaier** [comment]
Thanks for the release as for me it's just easier if there is one! :)
