### ISSUE TITLE
dhtnode: log to stdout but no prompt

### ISSUE THREAD

**Issue by aviau** [savoirfairelinux/opendht#198]
I'd like a daemon mode that:
 - does not fork
 - does not use syslog
 - logs to stdout

Currently, daemon mode forks and uses syslog.

Maybe add an option  --no-interactive?

This would be more systemd-friendly.

**Comment by aberaud** [comment]
Hi,
I just pushed a "service" mode (-s or --service), similar to what is already in dhtcluster.
In this mode, dhtnode doesn't fork, doesn't use stdin, and logs to stdout/stderr by default (unless --syslog or --logfile are used)

**Comment by aviau** [comment]
Very nice!

Can you make a release? I'll upload it to Debian right away. My next debian package will include the dhtnode service.

**Comment by aviau** [comment]
Works well here!

**Comment by aberaud** [comment]
@aviau Thanks for the Debian update.
I don't know the "official" way to comment about the Debian packaging ?

I think both patches in https://anonscm.debian.org/cgit/collab-maint/opendht.git/tree/debian/patches are no longer necessary:
- multiarch.patch is not needed because CMakeLists.txt already includes the GNUInstallDirs plugin (line 
- pkgconfig-static.patch: the pkgconfig file should already be well suited to link static packages: gnutls and nettle should be linked because of the `Requires.private: gnutls` line. Since the system argon2 is used, @argon2_lib@ should be replaced appropriately to link with argon2.

**Comment by aviau** [comment]
The official way would be to open a bug. Or you can always send me an email.

> multiarch.patch

Right, this was an old patch. I have removed it.

> pkgconfig-static.patch

For some reason this is needed for Ring. It should be investigated.

I am getting the following error:
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libopendht.a(crypto.cpp.o): undefined reference to symbol 'nettle_gcm_aes_decrypt@@NETTLE_6'
//usr/lib/x86_64-linux-gnu/libnettle.so.6: error adding symbols: DSO missing from command line
```
