### ISSUE TITLE
Instructions about dependencies

### ISSUE THREAD

**Issue by NicoHood** [savoirfairelinux/opendht#22]
Edit: Okay I totally overlooked this page:
https://github.com/savoirfairelinux/opendht/wiki/Build-the-library

However it is very confusing that the readme has a few details like this already written down, but not fully. I'd stick to the wiki only.

This is how I solved it (For Ubuntu 14.04 LTS). I installed msgpack a bit different (official instructions)
```bash
# Install msgpack
git clone https://github.com/msgpack/msgpack-c.git
cd msgpack-c/
export CXXFLAGS="$CXXFLAGS -std=c++11"
./bootstrap
./configure
make
sudo make install
cd ..

# Install other dependencies
sudo apt-get install nettle-dev libgnutls28-dev libreadline-dev

# Now follow the build instructions
https://github.com/savoirfairelinux/opendht#how-to-build-and-install
```

<hr>

Oh and while I might have the chance to ask a few questions:
In [this post](https://blog.savoirfairelinux.com/en/2015/ring-opendht-a-distributed-hash-table/) you wrote:

> Since we needed these crucial features for the Ring project, we wew pushed to create OpenDHT with the counterparty to make its protocol incompatible with the Mainline DHT network of BitTorrent.

I do not understand what this means. Other passages say it uses the same mechanism. The only thing that matters for me is the question: Will it use the same nodes? I mean having a lot nodes is important for such a system as far as I understood. Does opendht use a different network here, so we might have less nodes at the beginning of this new library? Or can we also rely on the thousands of nodes around which are already used for torrent downloading?

But dont I have to run a daemon to serve as node too? Does this only work as long as I open my program? Even though I do not want it, wouldnt it make sense to provide it as service in the system (just theoretical, in real world i want to turn it off if the program is closed)?

<hr>
Also it is unclear for me where the API stores my private key, and how to add a public key from someone else. But I might just need to test the examples.

<hr>
It'll be also interesting if the code works on Raspberry Pi (ARM Processors) as well.

<hr>
On your contact page is no PGP key given. Not even a ring ID to contact to ;)
No keyserver has the PGP key for your mail. Could you please add it?
https://www.savoirfairelinux.com/contact

<hr>
Why is the ring domain ending with .cx? That sound suspicious to me first.

<hr>

You may close this issue of course. It would be nice if you could answer those questions :)

**Comment by aberaud** [comment]
Hi and thanks for your comments !

I just made a wiki page with more details about how to install OpenDHT dependencies on various systems :
https://github.com/savoirfairelinux/opendht/wiki/Build-the-library

Indeed msgpack is not packaged in Ubuntu so you will need to build it by hand.

We built OpenDHT and even Ring on the Raspberry PI and other embedded platforms in the past and it works well.

#### About key storage:
OpenDHT doesn't store anything on the filesystem by itself.
Calling `dht::crypto::generateIdentity()` will generate an RSA key pair and a certificate, in memory. 
They can be serialised and stored using the pack() method as follow :
```c++
auto id = dht::crypto::generateIdentity();
auto private_key = id.first;
auto certificate = id.second;

// serialize the private key
std::vector<uint8_t> key_data;
private_key->pack(key_data);

// save key to disk
std::ofstream key_file(key_path, std::ios::trunc | std::ios::binary);
key_file.write((char*)key_data.data(), key_data.size());
chmod(key_path.c_str(), 0600);

// serialize the certificate
std::vector<uint8_t> cert_ data;
certificate->pack(cert_ data);

// ...
```
They can also be serialised as msgpack objects using msgpack:
```c++
auto id = dht::crypto::generateIdentity();
auto private_key = id.first;

// serialize the private key
msgpack::sbuffer buffer;
msgpack::packer<msgpack::sbuffer> pk(&buffer);
private_key->msgpack_pack(pk);
```
The Wiki will be improved about this topic soon to also mention de-serialisation etc.

#### About compatibility with Mainline DHT (Bittorrent):
Indeed OpenDHT is not compatible with bitorrent DHT nodes. That's because those nodes can't store anything else than IP addresses (that for bitorrent are the IPs of the peers for a given torrent), while OpenDHT can store arbitrary values of up to 128 KB.

To have a working DHT network for Ring while the community is still young, Savoir-Faire Linux runs a few nodes that can also be used for bootstraping to the network on bootstrap.ring.cx (port 4222). I also run a few nodes on my server, and with all the Ring users (that also run a node) it forms a reasonably sized network to start with, of course not as big as the bittorrent network :-)

We took .cx because there was not so many Ring domains available, but we might migrate to a better one in the future.

**Comment by NicoHood** [comment]
> I just made a wiki page with more details about how to install OpenDHT dependencies on various systems :+1: 

Oh so I wasnt wrong. I thought I overlooked it, but you edited it while I was searching. Looks better now, I've edited the post above with my instructions if you havent seen it. On kali2 I needed to install a package to run the configure command or so, but that was a quick google.

> while OpenDHT can store arbitrary values of up to 128 KB.

In the blogpost I think you wrote 64kb. I remember 100% that somewhere 64kb was mentioned.

**Please add this information also to the wiki or FAQ. That made it clear now!**

> I'd like to see Ring also on github, for simpler issue reporting. I've found a lot of issues, but you might be already aware of it, since its alpha.

<hr>
I guess you noticed the PGP comment.

**Comment by aberaud** [comment]
Yes the maximum size have increased when we moved from bencoding to msgpack for serialisation.

Thanks for all your suggestions ! We plan to have a GitHub repo for Ring "soon".

**Comment by NicoHood** [comment]
The wiki is missing `nettle-dev` as package.
I didnt want to edit it myself to not mess with your structure.

I'd edit how to compile on a raspi when I am done with it, if its okay. If not you should probably block wiki editing by others.

**Comment by NicoHood** [comment]
Okay just added it here. Seems to compile on a raspi, but still got those examples not working.
https://github.com/savoirfairelinux/opendht/wiki/Build-the-library/_compare/1f606c57682176a9640bff4b1e4244d0a3c5e2df

The readme is missing the readline dependency:
https://github.com/savoirfairelinux/opendht#dependencies

I suggest to fully move the docs to the wiki. That is really confusing and you have to patch back everything from the wiki. Also this gives less "trash" commits to the git history.

If you draft a [release at github](https://github.com/savoirfairelinux/opendht/releases) I suggest to add the current state of the wiki as documentation. Thats what I do for my projects at least.

**Comment by NicoHood** [comment]
I tried the readme example. To compile it you need to do one step more:
```bash
export LD_LIBRARY_PATH=/usr/local/lib/
g++ main.cpp -std=c++11 -lopendht -lgnutls
```

As suggested I'd move it to the wiki.

**Comment by aberaud** [comment]
Thanks for your contributions, you're welcome to edit the Wiki and to propose pull requests.

Note that I've simplified the build instructions to only keep the previous set of instructions to build msgpack for a few reasons (both methods do work fine) :
* Msgpack-c already broke their API in the past, so to guarantee compatibility we stick to tested releases (1.3 for now) instead of the Git master.
* CMake seems to be the primary build method for Msgpack-c. Many build options are not available with Autotools, and adding `-DMSGPACK_CXX11=ON` is cleaner than exporting custom `CXXFLAGS` (that may impact compilation of other projects afterward).
* I think it would be clearer with a single set of instructions.

I also edited the build instructions so OpenDHT is installed to `/usr` instead of `/usr/local`. That should simplify the process for most people, and the ones who know what that implies have the freedom to change it if they want.

The wiki will continue to be updated in the next days.

**Comment by NicoHood** [comment]
Shouldnt we then also install msgpack to `/usr/` or would this cause trouble?

To uninstall/move I think I have to move/delete those files, right? `ls /usr/local/lib/ | grep libopendht`

**Comment by aberaud** [comment]
You're right, I also added the `/usr` prefix to msgpack.

The typical install process will put the library in `/usr/local/lib/libopendht(.so|.a)`, the pkgconfig file in `/usr/local/lib/pkgconfig/opendht.pc` and headers in `/usr/local/include`.

**Comment by NicoHood** [comment]
Thanks for the information.
You also missed that in the readme. As already said, I'd completely remove this information from the readme to the wiki, to avoid such problems.
