### ISSUE TITLE
Add the ability to use mqtt for FDroid

### ISSUE THREAD

**Issue by AmarOk1412** [savoirfairelinux/opendht#241]
Just an idea from @pierreduchemin.

Looks easy to implement (just modify the flag "Android"/"iOS" to something like "Android-push"/"Android-mqtt"/"iOS" and host a mqtt server (or see if gorush can do that).

**Comment by pierreduchemin** [comment]
Java library for Mqtt protocol, compatible with Android :
https://eclipse.org/paho/clients/java/

List of Mqtt brokers :
https://github.com/mqtt/mqtt.github.io/wiki/servers

**Comment by AmarOk1412** [comment]
From IRC: https://f-droid.org/en/packages/org.androidpn.client/ <= for FDroid users!

**Comment by testbird** [comment]
Mqtt seems very centralized and requires external infrastructure, just as any other gatekeeper's system.

Piggybacking on existing IMAP-push infrastructure may be another option.
Possibly with a proof-of-concept patch to an existing, working IMAP-push app, to let the external app wake up Ring (call an intent) when it receives a wake-up email from a dht proxy.
https://git.ring.cx/savoirfairelinux/ring-client-android/issues/262#note_8034
Later, this mechanism could possibly be refactored into a more generic notification push client.
https://gitlab.com/foss-push/planning/wikis/home
e.g. https://github.com/deltachat/deltachat-core/issues/193#issuecomment-398175423
However, IMAP-push would still bring a dependency on another service, that is federated and not decentralized. 

So instead, it might also be an option to extent the existing dht proxy feature, and implement a push solution that could even work on libre hardware devices running independent OS distributions without vendor servers:

 - [x] Subscribe and watch mechanisms with periodic keep-alives.
 - [ ] TCP connections with longer NAT timeouts and keep-alive requirements (14 minutes).
 - [ ] On the clients, an ongoing looping watchdog thread to hold and renew the connection.
 - [ ] Watching/subscribing to network status change events, to stop and restart the thread accordingly.
 - [ ] On android, setting a permanent notification only while the display is turned off, to keep the thread running.
 - [ ] Timers to check for and restart the watchdog thread in case of error.
 

Implemented examples may be found in deltachat:
https://github.com/deltachat/deltachat-core
https://deltachat.github.io/api/
https://github.com/deltachat/deltachat-android

**Comment by testbird** [comment]
Had another look.

The DHTproxy-DirectPUSH would solves reaching ring peers that are currently online, but not those that are currently offline or any other email contact.

To allow contacting offline peers and arbitrary email addresses will need integrating a suitable email messaging lib, and providing a webrtc based server that classic email recipients (not using the email messaging lib) can connect to using their browser. 

It seems implementing the interaction in the basic libs (rather than on the frontend side) would be best, to avoid dependencies on specific clients (e.g. QT) and OSes (e.g. android) and have it work equally on all platforms and frontends.

Thus,
=> libring using deltachat-core for offline messaging (also receiving chat messages following the Email-chat spec) and initiating calls to contacts that are currently not present ub the p2p openDHT network  (imap-push wake-up messages).
=> deltachat-core using libring (not LibRingClient) to set up calls, and

https://github.com/deltachat/deltachat-core/issues/44#issuecomment-402648216

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by aberaud** [comment]
Now supporting gorush and openpush
