### ISSUE TITLE
How do I remotely curl to a proxyserver node on AWS?

### ISSUE THREAD

**Issue by science-girl** [savoirfairelinux/opendht#342]
I want to run a proxyserver node on an AWS EC2 instance.  I have opened HTTP, SSH, and all TCP and UDP port traffic on the AWS instance, and can successfully ping and send TCP packets using netcat. I create 2 nodes on the EC2 instance:

```dhtnode -p 2600``` and also ```dhtnode -b <public_ip>:2600 --proxyserver 80```

I then try to curl from a remote machine:
```curl <public_ip>:8080```
```curl: (7) Failed to connect to <public_ip> port 2600: Connection refused```

My understanding was that I could run a proxyserver node without having to run a client.  Is this correct?   
 Or is there something I'm not configuring properly?

**Comment by AmarOk1412** [comment]
Hi!

+ `dhtnode -p 2600` will instantiate a node (A) running on port 2600 (using for example `ip_a` as its public ip)

+ `dhtnode -b <public_ip>:2600 --proxyserver 80` will instantiate another node (B) to the first AND run a proxy server on port 80 (using `ip_b`). So you will have B (with a proxy) connected to A (via UDP).

I think what you want is:

+ (A) `dhtnode -p 2600 -b -proxyserver 80` (AWS side)
+ (B) `dhtnode -b <ip_a>:2600 --proxyclient <ip_a>:2600` (client side) to connect the node to the proxy server via Proxy (TCP). **NOTE** `-b <ip_a>:2600` is just to init its ip. You can replace this by `-p 5000` for example, or another network.
+ (C) `dhtnode -b <ip_a>:2600` (client 2) to connect (UDP) to the same network as A and B.

Anyway I think your error is to use `--proxyserver` instead of `--proxyclient`.

**Comment by aberaud** [comment]
@science-girl "My understanding was that I could run a proxyserver node without having to run a client. Is this correct?"

You can run a proxy server node without having HTTP clients connected to it. The proxy server can support from zero to a virtually unlimited number of clients (limited by machine ressources).

**Comment by science-girl** [comment]
Thank you so much for the quick and informative replies!  Sorry for typos, should be ```dhtnode -b <public_ip>:2600 --proxyserver 8080``` because you can't bind to port 80.

What ended up working was allowing 'all traffic' for my AWS security group.  Obviously this isn't optimal and I will have to work on figuring out which rules are needed.  If anyone can offer insight, that would be much appreciated.

**Comment by AmarOk1412** [comment]
The bootstrap node will sync with the rest of the network via UDP.
