### ISSUE TITLE
Callback when a new node joins or leaves network

### ISSUE THREAD

**Issue by nadendlaprasad** [savoirfairelinux/opendht#359]
Hi,

This is not an issue. But I would like to know if opendht is providing any callback function facility to know when a new node joins or leaves network.

**Comment by aberaud** [comment]
Hi,
Not currently,

The closest would be to do a listen at some hardcoded key related to your service, and to do a permanent put at that key when starting the node.

That would allow to have authentication (since values can be signed) and to have different services exposed on a single dht network (or even multiple services behind a single dht node).

Hopping this helps

**Comment by nadendlaprasad** [comment]
But problem over here is that If a node is down then how would other nodes in the network will get to know ? do you mean make another put with the status saying that node status is disconnected ?

**Comment by aberaud** [comment]
Yes if you require instant disconnection you would need to publish a "disconnection" value when leaving the network.

Since this seems to be a common use case I will think about how to abstract it in OpenDHT for future versions

**Comment by nadendlaprasad** [comment]
Thank you very much. Very good to hear that you are planning to include this feature.
