### ISSUE TITLE
[autotools] make uninstall doesn't remove python files

### ISSUE THREAD

**Issue by kaldoran** [savoirfairelinux/opendht#45]
Hi,

Here is the problem, when i use autotools [ Autogen script and configure script ], then make, and then sudo make install, all goes right.

But if you try to use `make uninstall` (as sudoers ), the command succeed but some files are still here (probably all are still here).

Here is the output of `make uninstall`
http://pastebin.com/a3WBC8dG
At the end you could also see the `ls` that shows that all file are still here.

**Comment by sim590** [comment]
On what revision (commit) have you tried this?

**Comment by kaldoran** [comment]
Last commit of Master branch.

**Comment by sim590** [comment]
Your log seems to indicate you're using a makefile configured on a different branch. It seems you were on branch `index` since the keywords `pht.h` and `pht_cache.h` appear. Especially since the word `pht_cache.h` is there, I can't say if your makefile is alright. Can you make sure to run the following on master branch and see if include files are still not removed.
```sh
$ make clean
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install
$ sudo make uninstall
$ find /usr/include -name \*opendht\*
```
As of the master branch, *autotools doesn't seem to delete installed python files*. This could be improved by adding a rule `uninstall-local:` to clean corresponding python files.

**Comment by kaldoran** [comment]
First, i was trying of another branch, but i re-did it into master and got the same problem.
[ i did not update the pastebin file]. 
I'll update it after this message

**Comment by kaldoran** [comment]
Ok, so between my 2 tests i manually remove the file that was giving trouble.
And now, i've done what you said above and no file are generate.

**Comment by sim590** [comment]
Alright. I'll modify your issue name and leave it opened for the case of python files which are not removed when doing `make uninstall` as I said above.

**Comment by kaldoran** [comment]
Since the PR had been merge i could close this issue :)

**Comment by Zibri** [comment]
make uninstall
make: *** No rule to make target 'uninstall'.  Stop.

**Comment by sim590** [comment]
@Zibri: I suspect, you're using CMake. This thread is about Autotools.
