### ISSUE TITLE
Enhancement: Drop all but N values

### ISSUE THREAD

**Issue by linas** [savoirfairelinux/opendht#462]
I'm interested in having the local node drop all but one (all but N) values of a given `ValueType`  I was hoping that `StorePolicy` and `EditPolicy` could be used to do this, but that is not the case.  I have two related issues:
1) Usually, I  am interested in keeping only the latest value (as they change over time)
2) I want to eliminate duplicate values. I can kind-of do this by assigning duplicates the same id, but this requires computing a 64-bit id :-(  Yuck.

This is particularly problematic if the expiration time in the `ValueType` is set to days or months, while a new value is published every few seconds. It's easy to accumulate thousands or millions of stale, dead values.

Related issues are:
* #429 -- ability to delete values
* #365 -- ability to listen only for the latest
* #280 -- ability to listen to all.

**Comment by aberaud** [comment]
> Usually, I am interested in keeping only the latest value (as they change over time)

> I want to eliminate duplicate values. I can kind-of do this by assigning duplicates the same id, but this requires computing a 64-bit id :-( Yuck.

Have you considered value edition (possible/supported with signed values) ?

**Comment by linas** [comment]
I have not yet tried to crypto-sign values, although I eventually plan to. But even so, there is no API to control this:  I have:
```
using StorePolicy = std::function<bool(InfoHash key, std::shared_ptr<Value>& value, const InfoHash& from, const SockAddr& addr)>;
using EditPolicy = std::function<bool(InfoHash key, const std::shared_ptr<Value>& old_val, std::shared_ptr<Value>& new_val, const InfoHash& from, const SockAddr& addr)>;
```

The edit policy is called only if `old_val->id == new_val->id` if the `id`'s are different, then only `StorePolicy` is called.   So first, I have to make sure that I issue exactly the same `id` when `put()`ing values.  (and so, depending on the situation, I have to "compute it", which is sometimes non-trivial.) But also: `old_val` is declared `const` so I cannot edit the old val. I can only edit the new val... but what I want is to discard the old val (or edit it to be empty) and keep the new val, unchanged.

Also, it can happen that neither  StorePoliy or EditPolicy are called; this can happen when `dhtRunner::put(...DoneCallback...)` tells me that `success==false`. Then, later on (seconds later?) a distant node gets the updated value, but neither StorePolicy or EditPolicy are called when this value arrives.

**Comment by linas** [comment]
Wow. Please ignore the comment above. I am trying to reproduce my work from a few days ago, and the system now seems to be behaving very differently than before, and I am finding the situation quite confusing.

**Comment by linas** [comment]
OK, here is what is happening today.  First, a snippet of my code that implements edit policy:
```
bool DHTAtomStorage::cy_edit_policy(dht::InfoHash key,
                              const std::shared_ptr<dht::Value>& old_val,
                              std::shared_ptr<dht::Value>& new_val,
                              const dht::InfoHash& from,
                              const dht::SockAddr& addr)
{
   std::string satom = new_val->unpack<std::string>();
#define REMOVE_ATOM "(cog-remove "
   if (0 == satom.compare(0, sizeof(REMOVE_ATOM)-1, REMOVE_ATOM))
   {
      // Asking for atom to be deleted from the atomspace.
      // Honor the request.
      new_val = std::make_shared<dht::Value>(_space_policy, "", old_val->id);
printf("deleted this: %s\n", satom.c_str());
      return true;
   }
   // Avoid birthday paradox
   return false;
}
```
And now for what is happening.  Please exuse the non-stanard representation; this is a scheme wrapper arround DHT:
```
(store-atom (Concept "foo"))
; The above causes "foo" to be added to the DHT, as seen below:
(display (dht-examine "d2bf1fd0312cbf309df74c537bea16769b419f44"))
Found 2 values
Member id=3ac7a3f3ac148907 seq=0 (ConceptNode "foo")
Member id=4b856ccc7c6d1789 seq=0 (PredicateNode "*-TruthValueKey-*")
; Good!
(cog-delete (Concept "foo"))

; Did the edit policy work as expected?  No...
(display (dht-examine "d2bf1fd0312cbf309df74c537bea16769b419f44"))
Found 3 values
Member id=3ac7a3f3ac148907 seq=0 
Member id=4b856ccc7c6d1789 seq=0 (PredicateNode "*-TruthValueKey-*")
Member id=3ac7a3f3ac148907 seq=0 (cog-remove (ConceptNode "foo"))
```
So, the edited new value was saved (that's the empty string)  But the unedited new value was also saved (the one starting with `cog-remove`).   Yuck.

**Comment by linas** [comment]
I can now reproduce the situation where `EditPolicy` is never called. 

My test setup involves two nodes, both on `localhost` one on port 4444 the other on port 4242. The second one is told to bootstrap from the first.  This is supposed to be a "private net", for my testing only.   Last night, I left it running. This morning, there were 30 external IP's who had contacted these servers and left data with them.  I think it's Jami, and its doing a port-scan and finds my private net.   One the system reaches this state, then `EditPolicy` is never called.  Maybe this is a side-effect of rate-limiting? Maybe traffic from these other IP's triggers rate limiting, and so prevents `EditPolicy` from being called?  Even though it is not called, the new value *is* published, and so now I get a system with multiple values for the same ID ...

**Comment by aberaud** [comment]
`But also: old_val is declared const so I cannot edit the old val. I can only edit the new val... but what I want is to discard the old val (or edit it to be empty) and keep the new val, unchanged.`

If value edition succeeds, the old value should be replaced by the new value, so the old value would somehow be "discarded". If you implement a custom value type that can be edited, I suggest to add some sort of sequence number or timestamp to guarantee forward progression (avoid older values replacing newer values).

`The system behaves very differently, depending on whether rate-limiting has kicked in, or not. There are two ways for rate-limiting to kick in. (1) I send messages too quickly on local host, or (2) my private network, running on non-standard ports, accidentally or on purpose connects to the Jami DHT network.`

That makes sense, because if you use custom value types, your network should only have nodes supporting your custom value type (for security and simplicity, value types are currently hardcoded in the nodes, so if a node doesn't support your custom type it will fallback on the default type).

So if your nodes with custom value types accidentally connect to the main network, the custom values types won't work as expected.

If you want to isolate your network from the main public network to avoid accidental merge, you can simply choose a specific network ID (for example used netID 5 in my test code in https://github.com/savoirfairelinux/opendht/issues/429#issuecomment-549485781 )

**Comment by linas** [comment]
Hmm. OK. I guess I can make that work.  Now that I understand the sources of the various bits of confounding behavior, I think I can deal with each.  

I'll close this bug for now, although the part about having `EditPolicy` with `new_val = std::make_shared<dht::Value>(...)` in it resulting in two "new values" is .. strange.
