### ISSUE TITLE
OPENDHT_C_PUBLIC dht_value* dht_value_new(const uint8_t* data, size_t size);

### ISSUE THREAD

**Issue by ghenry** [savoirfairelinux/opendht#582]
Hi all,

I'm having trouble with this function:

https://github.com/savoirfairelinux/opendht/blob/ace3a94e08efc753f702d7d607d6b9acee6328f8/c/opendht_c.h#L84

 when it's used in `dhtcnode.c`:

https://github.com/savoirfairelinux/opendht/blob/ace3a94e08efc753f702d7d607d6b9acee6328f8/tools/dhtcnode.c#L91

`Passing 'const char [22]' to parameter of type 'const uint8_t *' (aka 'const unsigned char *') converts between pointers to integer types where one is of the unique plain 'char' type and the other is not`

Does `dht_value_new` need to be an unsigned char/uint8_t? rather than just const char* 

If I switch `data_str` then `strlen` complains.

Thanks.

**Comment by ghenry** [comment]
I've cast with strlen, but wanted to check...

**Comment by aberaud** [comment]
A dht value can be created from any binary data. The C node example builds it from a string.
The obvious fix for the warning would be to cast the string to `const uint8_t*`.

Since building a value from string might be a common use-case, I added
```c++
dht_value* dht_value_new_from_string(const char* str)
```
in https://github.com/savoirfairelinux/opendht/pull/584

The implementation is mostly the same as calling:
```c++
dht_value_new((const uint8_t*)str, strlen(str));
```

It also sets the user-type field to `text/plain`, allowing to see the string value from dhtnode.

**Comment by ghenry** [comment]
Morning,

Understood.  A cast is what I did in the end.

Thanks for thinking of use C users :-) Great work as usual.
Gavin.
