### ISSUE TITLE
[PHT] complete nodes splitting

### ISSUE THREAD

**Issue by sim590** [savoirfairelinux/opendht#61]
Let `n_0` be a leaf in the PHT and `I_0`, a node on the DHT. When `n_0` is *full*, the next index insert involving `n_0` and performed by `I_0` will *split* the node in two leaves. As of now, the split consists only of `I_0` creating two *children* beneath `n_0`, i.e. two new leaves. `I_0` will then create a new entry in one of both new leaves and end the insert operation. However, left in this state, the "split" is not done yet. In theory, all entries in `n_0` should be "moved" to the corresponding new leaves. This is a mandatory behavior of the theoretical PHT.

### Solution

A simple and elegant way, suggested by @aberaud, would be to make use of the `listen` feature available from the DHT node. The idea is the following:

Let `p` a PHT key and `p_0` the longest prefix of `p` existing on the PHT. After inserting an index entry at `p_0`, i.e. `put(HASH(p_0), index_entry)`, you `listen` to the children `p_1`, `p_2` of `p_0` so that if `p_1` or `p_2` becomes a leaf, the index entry on `p_0` will be inserted to the associated child.

However, one should consider that:

- An index entry should not last longer on the PHT after being "moved" than it would have without, i.e. when "moving" the entry, a time stamp should be transferred. The signature of `put` let you do that by using the `created` parameter;
- *Moving an entry*: an entry is never moved, but only copied. Entries expire themselves.

**Comment by sim590** [comment]
@aberaud, do you have any thoughts to add?

**Comment by sim590** [comment]
@kaldoran: I think that such an enhancement make the PHT cache from #41 better.

**Comment by kaldoran** [comment]
Should have update this one a lot sooner but here comes the update.
Lot of version of this thing was done, with some try and error, a great version will came out son.

We finally choose to split until there is a difference between they key, and split until the point of splitting instead of split it recursively that will generate a lot of trafic.

For the merge, since the current version of merge is not relevant i'm going to change the method.
Instead of counting value in a triangle shape ( parent, current node and is sibling ) we are just going to stop update a canary when a put is done, only a split will update it.

**Comment by kaldoran** [comment]
So here is some update, @aberaud we speak about the idea of not updating the canary when we put another value.
But if you put some value with the same start, then the tries going to grow until the end of the common bits into thoses prefix.
Then, after some time, the canary will expire, but some value are still in the node where the split append, but for now they are unreachable ...

I try to use another method here, where i update the canary above the node where it split but not seams to work ..
Looking for others idea for now

**Comment by kaldoran** [comment]
Additional feedback here : 
@sim590 was saying that we should reput the data on the Pht and do not then restart he timer to zero ( for the expiration ).
I was planning on update my method to always keep the same time but i've found that the dhtrunner does not allow to choose the time where it was created ( but the dht api allow it ).

Should i use the dht api directly or should i open an issue about that, and create a PR that correct this problem and then allow to give the time_point which indicate when the data was created ?

**Comment by kaldoran** [comment]
Got another idea for the merge, maybe we could use the Scheduler, by adding a job which going to check if there is a canary on the current node ( where the data is ). 
if there is one, juste redo it in 5 min ( time of a canary / 2 ).

If there is a canary, then recheck into 5 min
else redo a pht insert.

Thats means that, in average, each data will be replace at the correct location in 5 min ( or less )

**Comment by kaldoran** [comment]
Any update on that please ?

**Comment by kaldoran** [comment]
When i did this gif : ![](http://i.makeagif.com/media/8-08-2016/8b811L.gif)

I understand something, in this case the value would be duplicate a lot ( since in the depth of 1 [ROOT > depth 1 > 2 etc .. ] ) we put 2 values from above, then they would move to leaves when the depth 2 comes .. 
If this append the, at depth 2 we got the 16 values from above +  2 duplicated ..
If we continue so on then lots of values would be duplicate.
