### ISSUE TITLE
OpenDHT does not build on armel.

### ISSUE THREAD

**Issue by aviau** [savoirfairelinux/opendht#87]
OpenDHT does not build on armel, see the following log:
 - https://buildd.debian.org/status/fetch.php?pkg=ring&arch=armel&ver=20160630.2.b3d131f~dfsg1-2&stamp=1467369556

This is the only Debian-supported architecture that OpenDHT does not build on.

Note: I am able to sponsor access to Debian porter machines. See the [documentation](https://dsa.debian.org/doc/guest-account/) on requesting access.

**Comment by sim590** [comment]
I've begun testing on armel archetecture in order to reproduce and find the bug. I'll update shortly.

**Comment by sim590** [comment]
So the issue is definitely [this](https://lists.debian.org/debian-arm/2013/12/msg00007.html), i.e. that `std::future` templates are not supported on armel archetecture.

@aberaud: A solution would be to use the following to disable `std::future` signatures when not supported.
```cpp
#if defined(_GLIBCXX_HAS_GTHREADS) && defined(_GLIBCXX_USE_C99_STDINT_TR1) && (ATOMIC_INT_LOCK_FREE > 1)
```
I know that [ring](https://github.com/savoirfairelinux/ring-daemon/blob/master/src/ringdht/ringaccount.cpp#L241) uses this feature. I'm looking for a solution for this too.

**Comment by sim590** [comment]
@aviau: Actually, if you look at `DhtRunner`, you can see that std::future is used for blocking on the dhtrunner internal ops queue. So, if I were to use the fix above, I'd have to implement handling of `listen` token return in another way which would mean a bit of code to write and it wouldn't be really beautiful with many `ifdef` statements. We have to ask ourselves if this is worth supporting armel archetecture.

**Comment by aviau** [comment]
If the fix isn't too complicated, I would love to see it merged. Otherwise, I could even maintain it in Debian. All of the other Ring dependencies already build on armel. Future armel-incompatible changes will be spotted easily because the Debian CI will constantly build OpenDHT.

**Comment by aberaud** [comment]
Do we **need** to support ARMv5 to be in Debian ?
This architecture is obsolete, every chip is at least ARMv7. If it doesn't support std::future it should really not our problem, we won't re-implement the weel just for that. _OpenDHT requires C++11 support._

Ring also makes use of std::future.

**Comment by sim590** [comment]
> Do we need to support ARMv5 to be in Debian ?
This architecture is obsolete, every chip is at least ARMv7. If it doesn't support std::future it really shouldn't be our problem, we won't re-implement the weel just for that. OpenDHT requires C++11 support.

I'll let @aviau debate over this. IMO, I don't think this is necessary. Since our main page claims OpenDHT is a *C++11* library, I think that the lack of support for the armel architecture is consistent.

> Ring makes use this OpenDHT API and of std::future in other places so it would also require work in Ring.

**OpenDHT is not binded to Ring**. If the Ring project doesn't choose to support armel, this is fine. The discussion should stick to OpenDHT. If we want to speak about Ring we should do it [there](https://tuleap.ring.cx/plugins/tracker/?aid=815).

**Comment by aviau** [comment]
> Do we need to support ARMv5 to be in Debian ?

No, this is not a requirement.

However, should somebody want to run OpenDHT on debian/armel and send us a patch,  we will ship a patched version of OpenDHT in Debian.

**Comment by aberaud** [comment]
> OpenDHT is not binded to Ring.

Sure, just wanted to make it clear that an OpenDHT patch woudn't be enough to support ARMv5 in Ring.

> No, this is not a requirement. However, should somebody want to run OpenDHT on debian/armel and send us a patch, we will ship a patched version of OpenDHT in Debian.

Will OpenDHT have it's own Debian package ? 😀

The thing is, std::future is part of the core OpenDHT API. Not using it would mean to have a different core API between architectures which is very ugly and cumbersome for both us and API users. The only clean fix would be to add std::future support to armel (does clang have the same limitation?) or to cripple OpenDHT features.

**Comment by sim590** [comment]
> Will OpenDHT have it's own Debian package ?

@aviau was actually working on creating a package for OpenDHT if I'm not mistaken.
